Fixed files
MrSkorohod/HiQo pull request #2
Opened 2021-07-01 06:59 UTC by MrSkorohod

Reorganizing files. Adding a package.json and gulpfile. Adding classes according to the BEM methodology.

2021-07-01 07:35 UTC, ElizavetaSelivanova commented
Incorrect branch naming.

2021-07-01 07:42 UTC, ElizavetaSelivanova requested changes

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on .gitignore
> +dist/
Add an empty line to the end of file

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/base/_typography.scss
> +.headerNavigation {
Classname - try to not use camel-case for classes

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/base/_typography.scss
>    font: 600 16px / 24px $text-font;
You can try to add mixins for fonts

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/base/_typography.scss
> +.design-cards{
Add space before '{'

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/layout/_footer.scss
> +  .yellow-button{
Are you sure this is the correct class name? What happens if the colors will be changed =)

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/layout/_section-design-tools.scss
> +  .design-cards{
empty space before new class

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/layout/_section-news.scss
>    border-bottom: 1px solid $light-grey  ;
Remove spaces before `;`

2021-07-01 07:42 UTC, ElizavetaSelivanova commented on stylesheets/main.scss
>  'layout/section-design-tools',
Fix alignment

2021-07-02 09:25 UTC, angelinabylitskaya commented
Closed due to wrong branching strategy.

2021-07-02 09:25 UTC, closed without merging